"""York/TCL TFIAC protocol adapter components."""

from adapters.york.broadlink import (
    BroadlinkYorkLowVerticalTemperatureWriteClient,
    BroadlinkYorkOneShotWriteClient,
    BroadlinkYorkReadClient,
    BroadlinkYorkTemperatureWriteClient,
    YORK_QUALIFICATION_COOL_22_TO_25,
    YORK_QUALIFICATION_HEAT_23_TO_24,
    YORK_QUALIFICATION_HEAT_HIGH_VERTICAL_24,
    YORK_QUALIFICATION_HEAT_HIGH_VERTICAL_26,
    YORK_QUALIFICATION_HEAT_HIGH_VERTICAL_16,
    YORK_QUALIFICATION_HEAT_HIGH_VERTICAL_31,
    YORK_QUALIFICATION_HEAT_LOW_VERTICAL_24,
    YORK_QUALIFICATION_HEAT_LOW_VERTICAL_25,
    YORK_QUALIFICATION_HEAT_LOW_BOTH_21_5,
    YORK_QUALIFICATION_HEAT_LOW_HORIZONTAL_21_5,
    YORK_QUALIFICATION_HEAT_LOW_OFF_21_5,
    YORK_REJECTED_ALPHA49_HEAT_LOW_HORIZONTAL_21_5,
    YORK_QUALIFICATION_HEAT_LOW_VERTICAL_21_5,
    YORK_QUALIFICATION_DRY_LOW_BOTH_21,
    YORK_QUALIFICATION_DRY_LOW_VERTICAL_21,
    YORK_QUALIFICATION_POWER_OFF,
    YORK_QUALIFICATION_POWER_OFF_HEAT,
    YORK_QUALIFICATION_POWER_ON,
    YORK_QUALIFICATION_POWER_ON_COOL,
    YORK_QUALIFICATION_POWER_ON_HEAT,
    YORK_STATE_QUERY,
    YorkOneShotWriteResult,
)
from adapters.york.temperature_command import (
    build_qualified_temperature_command,
    validate_qualified_temperature_command,
)
from adapters.york.captured_temperature_command import (
    CAPTURED_TEMPERATURES,
    MAX_QUALIFIED_TEMPERATURE,
    MIN_QUALIFIED_TEMPERATURE,
    QUALIFIED_TEMPERATURES,
    build_captured_heat_high_vertical_temperature_command,
    validate_captured_heat_high_vertical_temperature_command,
)
from adapters.york.low_vertical_temperature_command import (
    CAPTURED_LOW_VERTICAL_TEMPERATURES,
    MAX_LOW_VERTICAL_TEMPERATURE,
    MIN_LOW_VERTICAL_TEMPERATURE,
    QUALIFIED_LOW_VERTICAL_TEMPERATURES,
    build_captured_heat_low_vertical_temperature_command,
    validate_captured_heat_low_vertical_temperature_command,
)
from adapters.york.connection import YorkConnection
from adapters.york.decoder import YorkPacketDecoder
from adapters.york.encoder import YorkPacketEncoder
from adapters.york.session import YorkProtocolSession
from adapters.york.state import YorkState

__all__ = [
    "BroadlinkYorkReadClient",
    "BroadlinkYorkLowVerticalTemperatureWriteClient",
    "BroadlinkYorkOneShotWriteClient",
    "BroadlinkYorkTemperatureWriteClient",
    "YorkOneShotWriteResult",
    "YORK_STATE_QUERY",
    "YORK_QUALIFICATION_COOL_22_TO_25",
    "YORK_QUALIFICATION_HEAT_23_TO_24",
    "YORK_QUALIFICATION_HEAT_HIGH_VERTICAL_24",
    "YORK_QUALIFICATION_HEAT_HIGH_VERTICAL_26",
    "YORK_QUALIFICATION_HEAT_HIGH_VERTICAL_16",
    "YORK_QUALIFICATION_HEAT_HIGH_VERTICAL_31",
    "YORK_QUALIFICATION_HEAT_LOW_VERTICAL_24",
    "YORK_QUALIFICATION_HEAT_LOW_VERTICAL_25",
    "YORK_QUALIFICATION_HEAT_LOW_BOTH_21_5",
    "YORK_QUALIFICATION_HEAT_LOW_HORIZONTAL_21_5",
    "YORK_QUALIFICATION_HEAT_LOW_OFF_21_5",
    "YORK_REJECTED_ALPHA49_HEAT_LOW_HORIZONTAL_21_5",
    "YORK_QUALIFICATION_HEAT_LOW_VERTICAL_21_5",
    "YORK_QUALIFICATION_DRY_LOW_BOTH_21",
    "YORK_QUALIFICATION_DRY_LOW_VERTICAL_21",
    "YORK_QUALIFICATION_POWER_OFF",
    "YORK_QUALIFICATION_POWER_OFF_HEAT",
    "YORK_QUALIFICATION_POWER_ON",
    "YORK_QUALIFICATION_POWER_ON_COOL",
    "YORK_QUALIFICATION_POWER_ON_HEAT",
    "build_qualified_temperature_command",
    "validate_qualified_temperature_command",
    "CAPTURED_TEMPERATURES",
    "MIN_QUALIFIED_TEMPERATURE",
    "MAX_QUALIFIED_TEMPERATURE",
    "QUALIFIED_TEMPERATURES",
    "build_captured_heat_high_vertical_temperature_command",
    "validate_captured_heat_high_vertical_temperature_command",
    "CAPTURED_LOW_VERTICAL_TEMPERATURES",
    "MIN_LOW_VERTICAL_TEMPERATURE",
    "MAX_LOW_VERTICAL_TEMPERATURE",
    "QUALIFIED_LOW_VERTICAL_TEMPERATURES",
    "build_captured_heat_low_vertical_temperature_command",
    "validate_captured_heat_low_vertical_temperature_command",
    "YorkConnection",
    "YorkPacketDecoder",
    "YorkPacketEncoder",
    "YorkProtocolSession",
    "YorkState",
]
