"""Guarded one-shot qualification of York temperature range boundaries."""
from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from adapters.york import (
    BroadlinkYorkOneShotWriteClient,
    YorkPacketDecoder,
    build_captured_heat_high_vertical_temperature_command,
)
from adapters.york.broadlink import york_xor
from configuration import load_config
from version import APP_VERSION


@dataclass(frozen=True)
class TemperatureCase:
    name: str
    before_temperature: float
    target_temperature: float
    command: bytes
    confirmation_token: str
    source_reference: str
    expected_sha256: str

    @property
    def before(self) -> dict[str, Any]:
        return _state(self.before_temperature)

    @property
    def after(self) -> dict[str, Any]:
        return _state(self.target_temperature)


def _state(temperature: float) -> dict[str, Any]:
    return {
        "power": True,
        "mode": "heat",
        "temperature": float(temperature),
        "fan": "high",
        "swing": "vertical",
        "turbo": False,
        "eco": False,
        "health": False,
        "display": True,
    }


CASES = {
    "30-to-31": TemperatureCase(
        name="30-to-31",
        before_temperature=30.0,
        target_temperature=31.0,
        command=bytes.fromhex(
            "BB0001031901004401003D00000000000000000000000000000000000000D9"
        ),
        confirmation_token="WRITE-QUALIFIED-TEMPERATURE-30-TO-31-ONCE",
        source_reference=(
            "target frame from successful Relay v2 temperature transaction #7 "
            "(2026-07-30 13:52:25)"
        ),
        expected_sha256=(
            "b1a20475a10b9dd5181a4fac9eb66126fe2416545921944cef8df58324d33981"
        ),
    ),
    "31-to-16": TemperatureCase(
        name="31-to-16",
        before_temperature=31.0,
        target_temperature=16.0,
        command=bytes.fromhex(
            "BB00010319010044010F3D00000000000000000000000000000000000000D6"
        ),
        confirmation_token="WRITE-QUALIFIED-TEMPERATURE-31-TO-16-ONCE",
        source_reference=(
            "target frame from successful Relay v2 temperature transaction #5 "
            "(2026-07-30 13:51:33)"
        ),
        expected_sha256=(
            "7304bb1ebf387eff98ebd61eba08b3f71f64b41651b7a6cc817dcc9c3dda2012"
        ),
    ),
}


class QualificationSafeStop(RuntimeError):
    """Stop before a write when the live state is not exactly qualified."""


def _compare(expected: dict[str, Any], observed: dict[str, Any]) -> dict[str, Any]:
    fields = {
        key: {
            "expected": expected_value,
            "observed": observed.get(key),
            "match": observed.get(key) == expected_value,
        }
        for key, expected_value in expected.items()
    }
    matches = sum(int(item["match"]) for item in fields.values())
    return {
        "fields": fields,
        "matches": matches,
        "compared": len(fields),
        "result": "MATCH" if matches == len(fields) else "MISMATCH",
    }


def _validate_case(case: TemperatureCase) -> None:
    generated = build_captured_heat_high_vertical_temperature_command(
        case.target_temperature
    )
    if generated != case.command:
        raise SystemExit(
            f"SAFE STOP: {case.name} generated bytes differ from Relay capture"
        )
    if len(case.command) != 31:
        raise SystemExit(f"SAFE STOP: {case.name} command is not 31 bytes")
    if york_xor(case.command):
        raise SystemExit(f"SAFE STOP: {case.name} York checksum is invalid")
    if hashlib.sha256(case.command).hexdigest() != case.expected_sha256:
        raise SystemExit(f"SAFE STOP: {case.name} command fingerprint is invalid")


def _state_label(state: dict[str, Any]) -> str:
    return (
        f"On / Heat / {state['temperature']:g} °C / "
        "Fan High / Swing Vertical"
    )


def _print_case(case: TemperatureCase) -> None:
    print(f"Temperature {case.name.replace('-', ' To ')} case:")
    print(f"  Required live state: {_state_label(case.before)}")
    print(f"  Qualified result: {_state_label(case.after)}")
    print(f"  Generated command: {case.command.hex(' ').upper()}")
    print(f"  Command SHA-256: {hashlib.sha256(case.command).hexdigest()}")
    print(f"  Official Relay v2 source: {case.source_reference}")
    print("  Generator/capture match: exact (31/31 bytes)")
    print(f"  Confirmation token: {case.confirmation_token}")


def _write_report(
    output_dir: Path,
    case: TemperatureCase,
    payload: dict[str, Any],
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    version_tag = APP_VERSION.replace(".", "-")
    path = output_dir / f"{version_tag}-temperature-{case.name}-{stamp}.json"
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Validate Alpha.40's boundary-qualified Heat temperature frames or "
            "execute one guarded case once."
        )
    )
    parser.add_argument("config", nargs="?", default="/config/config.yml")
    parser.add_argument("--case", choices=tuple(CASES))
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--confirm", default="")
    parser.add_argument("--output-dir", default="/reports/direct-write")
    parser.add_argument("--post-write-delay", type=float, default=2.0)
    args = parser.parse_args()

    print(f"Climate Bridge {APP_VERSION} — Temperature One-Shot Qualification")
    config = load_config(Path(args.config))
    if not config.direct_read_enabled:
        raise SystemExit("SAFE STOP: direct_read.enabled must be true")
    if not config.direct_host or not config.direct_mac:
        raise SystemExit("SAFE STOP: direct host and MAC are required")

    for case in CASES.values():
        _validate_case(case)
    print(f"Target: {config.direct_host}:{config.direct_port}/udp")
    for case in CASES.values():
        _print_case(case)
    print("Qualified whole-degree range: 16 to 31 °C inclusive")
    print("Encoding proved by captures: setpoint byte = 31 - temperature")
    print("Automatic retries: 0")
    print("Automatic restore: disabled")
    print("Normal MQTT temperature path: unchanged; Relay v2 fallback remains active")

    if not args.execute:
        print("VALIDATION PASSED — no socket opened and no packet transmitted.")
        print("Execution requires --case plus that case's exact confirmation token.")
        return 0
    if args.case is None:
        raise SystemExit(
            "SAFE STOP: --case is required; no socket opened"
        )
    case = CASES[args.case]
    if args.confirm != case.confirmation_token:
        raise SystemExit(
            "SAFE STOP: exact confirmation token is required; no socket opened"
        )
    if not 0 <= args.post_write_delay <= 10:
        raise SystemExit(
            "SAFE STOP: post-write delay must be between 0 and 10 seconds"
        )

    decoder = YorkPacketDecoder()
    before_comparison: dict[str, Any] = {}

    def approve_precondition(frame: bytes) -> None:
        nonlocal before_comparison
        observed = decoder.decode_state(frame).to_dict()
        before_comparison = _compare(case.before, observed)
        if before_comparison["result"] != "MATCH":
            raise QualificationSafeStop(
                "live precondition mismatch "
                f"({before_comparison['matches']}/{before_comparison['compared']})"
            )

    client = BroadlinkYorkOneShotWriteClient(
        config.direct_host,
        config.direct_port,
        config.direct_mac,
        config.direct_connect_timeout,
        case.command,
    )
    started = datetime.now(timezone.utc)
    try:
        result = client.execute(
            approve_precondition,
            post_write_delay_seconds=args.post_write_delay,
        )
    except QualificationSafeStop as error:
        report = _write_report(
            Path(args.output_dir),
            case,
            {
                "schema_version": 1,
                "version": APP_VERSION,
                "case": case.name,
                "status": "safe_stop",
                "reason": str(error),
                "write_commands_sent": 0,
                "udp_sends": client.last_send_count,
                "before_qualification": before_comparison,
            },
        )
        print(f"SAFE STOP: {error}")
        print("Write commands sent: 0")
        print(f"Report: {report}")
        return 10

    before = decoder.decode_state(result.before_frame).to_dict()
    command_reply = decoder.decode_state(result.command_reply_frame).to_dict()
    after = decoder.decode_state(result.after_frame).to_dict()
    after_comparison = _compare(case.after, after)
    completed = datetime.now(timezone.utc)
    status = "passed" if after_comparison["result"] == "MATCH" else "failed"
    report = _write_report(
        Path(args.output_dir),
        case,
        {
            "schema_version": 1,
            "version": APP_VERSION,
            "case": case.name,
            "status": status,
            "source_reference": case.source_reference,
            "encoding": "byte[9] = 31 - whole-degree Celsius setpoint",
            "command": {
                "frame_hex": case.command.hex(" ").upper(),
                "sha256": hashlib.sha256(case.command).hexdigest(),
                "generated_from_capture_backed_formula": True,
                "write_commands_sent": 1,
            },
            "before_state": before,
            "command_reply_state": command_reply,
            "after_state": after,
            "before_qualification": before_comparison,
            "after_qualification": after_comparison,
            "udp_sends": result.send_count,
            "session_id": result.session_id,
            "started_utc": started.isoformat(),
            "completed_utc": completed.isoformat(),
            "safety": {
                "operator_triggered": True,
                "confirmation_token_required": True,
                "capture_backed_targets_only": True,
                "pre_read_required": True,
                "post_read_required": True,
                "automatic_retries": 0,
                "automatic_restore": False,
                "mqtt_command_path": False,
            },
        },
    )

    print(f"Before: {_state_label(before)}")
    print(f"After: {_state_label(after)}")
    print(
        f"Verification: {after_comparison['result']} "
        f"({after_comparison['matches']}/{after_comparison['compared']})"
    )
    print("Write commands sent: 1")
    print(f"UDP sends: {result.send_count}")
    print("Automatic retries: 0")
    print(f"Report: {report}")
    if status != "passed":
        raise SystemExit("QUALIFICATION FAILED — do not rerun automatically")
    print("QUALIFICATION PASSED — do not rerun this case.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
