"""Guarded one-shot qualification of uncaptured York temperature targets."""
from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from adapters.york import (
    BroadlinkYorkTemperatureWriteClient,
    YorkPacketDecoder,
    build_qualified_temperature_command,
    validate_qualified_temperature_command,
)
from configuration import load_config

APP_VERSION = "1.0.0-alpha.28"


@dataclass(frozen=True)
class QualificationCase:
    name: str
    mode: str
    before_temperature: float
    target_temperature: float
    confirmation_token: str
    expected_frame_hex: str
    expected_sha256: str

    @property
    def expected_before(self) -> dict[str, Any]:
        return {
            "power": True,
            "mode": self.mode,
            "temperature": self.before_temperature,
            "fan": "low",
            "swing": "off",
            "turbo": False,
            "eco": False,
            "health": False,
            "display": True,
        }

    @property
    def expected_after(self) -> dict[str, Any]:
        return {
            **self.expected_before,
            "temperature": self.target_temperature,
        }


CASES = {
    "heat": QualificationCase(
        name="heat",
        mode="heat",
        before_temperature=23.5,
        target_temperature=22.5,
        confirmation_token="WRITE-UNCAPTURED-HEAT-23P5-TO-22P5-ONCE",
        expected_frame_hex=(
            "BB0001031901004401090202000000000000000000000000000000000000ED"
        ),
        expected_sha256=(
            "048b2814020e6119baa087f93eac0f6d980020b78bda74dbfa2b426a57a83601"
        ),
    ),
    "cool": QualificationCase(
        name="cool",
        mode="cool",
        before_temperature=25.0,
        target_temperature=24.5,
        confirmation_token="WRITE-UNCAPTURED-COOL-25-TO-24P5-ONCE",
        expected_frame_hex=(
            "BB0001031901004403070202000000000000000000000000000000000000E1"
        ),
        expected_sha256=(
            "bb1289158a8647707f985b85c5958aa32d6d3d6ee2a8e46945d74f2f0b5fa7c4"
        ),
    ),
}


class QualificationSafeStop(RuntimeError):
    """Stop before a write when the live state is not exactly qualified."""


def _compare(expected: dict[str, Any], observed: dict[str, Any]) -> dict[str, Any]:
    fields: dict[str, dict[str, Any]] = {}
    for key, expected_value in expected.items():
        observed_value = observed.get(key)
        fields[key] = {
            "expected": expected_value,
            "observed": observed_value,
            "match": observed_value == expected_value,
        }
    matches = sum(int(item["match"]) for item in fields.values())
    return {
        "fields": fields,
        "matches": matches,
        "compared": len(fields),
        "result": "MATCH" if matches == len(fields) else "MISMATCH",
    }


def _validated_generated_command(case: QualificationCase) -> bytes:
    generated = build_qualified_temperature_command(
        case.mode, case.target_temperature
    )
    if generated.hex().upper() != case.expected_frame_hex:
        raise SystemExit(
            f"SAFE STOP: {case.name} generated bytes differ from the "
            "independently specified canonical fixture"
        )
    if hashlib.sha256(generated).hexdigest() != case.expected_sha256:
        raise SystemExit(
            f"SAFE STOP: {case.name} generated command fingerprint is invalid"
        )
    if validate_qualified_temperature_command(generated) != (
        case.mode,
        case.target_temperature,
    ):
        raise SystemExit(
            f"SAFE STOP: {case.name} generated command failed canonical validation"
        )
    return generated


def _write_report(
    output_dir: Path, case: QualificationCase, payload: dict[str, Any]
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    path = output_dir / f"alpha28-uncaptured-{case.name}-{stamp}.json"
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return path


def _print_case(case: QualificationCase, generated: bytes) -> None:
    print(f"{case.name.title()} case:")
    print(
        f"  Required live state: On / {case.mode.title()} / "
        f"{case.before_temperature:g} °C / Fan Low / Swing Off"
    )
    print(
        f"  Qualified result: On / {case.mode.title()} / "
        f"{case.target_temperature:g} °C / Fan Low / Swing Off"
    )
    print(f"  Generated command: {generated.hex(' ').upper()}")
    print(f"  Generated SHA-256: {hashlib.sha256(generated).hexdigest()}")
    print("  Fixture match: exact (31/31 bytes)")
    print("  Matching Relay v2 target capture: intentionally not used")
    print(f"  Confirmation token: {case.confirmation_token}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Validate Alpha.28's two uncaptured targets or execute one guarded "
            "case once."
        )
    )
    parser.add_argument("config", nargs="?", default="/config/config.yml")
    parser.add_argument("--case", choices=sorted(CASES))
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--confirm", default="")
    parser.add_argument("--output-dir", default="/reports/direct-write")
    parser.add_argument("--post-write-delay", type=float, default=2.0)
    args = parser.parse_args()

    print(
        f"Climate Bridge {APP_VERSION} — "
        "Uncaptured Heat/Cool Temperature Qualification"
    )
    config = load_config(Path(args.config))
    if not config.direct_read_enabled:
        raise SystemExit("SAFE STOP: direct_read.enabled must be true")
    if not config.direct_host or not config.direct_mac:
        raise SystemExit("SAFE STOP: direct host and MAC are required")

    generated_by_case = {
        name: _validated_generated_command(case)
        for name, case in CASES.items()
    }
    print(f"Target: {config.direct_host}:{config.direct_port}/udp")
    for name in ("heat", "cool"):
        _print_case(CASES[name], generated_by_case[name])
    print("Automatic retries: 0")
    print("Automatic restore: disabled")

    if not args.execute:
        print("VALIDATION PASSED — no socket opened and no packet transmitted.")
        print("Execution requires --case plus that case's exact confirmation token.")
        return 0
    if args.case is None:
        raise SystemExit(
            "SAFE STOP: --case heat or --case cool is required; no socket opened"
        )
    case = CASES[args.case]
    if args.confirm != case.confirmation_token:
        raise SystemExit(
            "SAFE STOP: exact confirmation token is required; no socket opened"
        )
    if not 0 <= args.post_write_delay <= 10:
        raise SystemExit(
            "SAFE STOP: post-write delay must be between 0 and 10 seconds"
        )

    decoder = YorkPacketDecoder()
    before_comparison: dict[str, Any] = {}

    def approve_precondition(frame: bytes) -> None:
        nonlocal before_comparison
        observed = decoder.decode_state(frame).to_dict()
        before_comparison = _compare(case.expected_before, observed)
        if before_comparison["result"] != "MATCH":
            raise QualificationSafeStop(
                f"live precondition mismatch "
                f"({before_comparison['matches']}/{before_comparison['compared']})"
            )

    started = datetime.now(timezone.utc)
    client = BroadlinkYorkTemperatureWriteClient(
        config.direct_host,
        config.direct_port,
        config.direct_mac,
        config.direct_connect_timeout,
        case.mode,
        case.target_temperature,
    )
    try:
        result = client.execute(
            approve_precondition,
            post_write_delay_seconds=args.post_write_delay,
        )
    except QualificationSafeStop as error:
        report = _write_report(
            Path(args.output_dir),
            case,
            {
                "schema_version": 1,
                "version": APP_VERSION,
                "case": case.name,
                "status": "safe_stop",
                "reason": str(error),
                "write_commands_sent": 0,
                "udp_sends": client.last_send_count,
                "before_qualification": before_comparison,
                "safety": {
                    "generated_command": True,
                    "uncaptured_target": True,
                    "automatic_retries": 0,
                    "automatic_restore": False,
                },
            },
        )
        print(f"SAFE STOP: {error}")
        print("Write commands sent: 0")
        print(f"Report: {report}")
        return 10

    generated = generated_by_case[case.name]
    before = decoder.decode_state(result.before_frame).to_dict()
    command_reply = decoder.decode_state(result.command_reply_frame).to_dict()
    after = decoder.decode_state(result.after_frame).to_dict()
    after_comparison = _compare(case.expected_after, after)
    completed = datetime.now(timezone.utc)
    status = "passed" if after_comparison["result"] == "MATCH" else "failed"
    report = _write_report(
        Path(args.output_dir),
        case,
        {
            "schema_version": 1,
            "version": APP_VERSION,
            "case": case.name,
            "status": status,
            "command": {
                "source": "qualified canonical generator; no matching target capture",
                "mode": case.mode,
                "target_temperature": case.target_temperature,
                "frame_hex": generated.hex(" ").upper(),
                "sha256": hashlib.sha256(generated).hexdigest(),
                "uncaptured_target": True,
                "write_commands_sent": 1,
            },
            "endpoint": {
                "host": config.direct_host,
                "port": config.direct_port,
                "mac": config.direct_mac,
            },
            "before_state": before,
            "command_reply_state": command_reply,
            "after_state": after,
            "before_qualification": before_comparison,
            "after_qualification": after_comparison,
            "udp_sends": result.send_count,
            "session_id": result.session_id,
            "started_utc": started.isoformat(),
            "completed_utc": completed.isoformat(),
            "elapsed_ms": round((completed - started).total_seconds() * 1000, 1),
            "safety": {
                "operator_triggered": True,
                "confirmation_token_required": True,
                "generated_command": True,
                "uncaptured_target": True,
                "pre_read_required": True,
                "post_read_required": True,
                "automatic_retries": 0,
                "automatic_restore": False,
                "mqtt_command_path": False,
            },
        },
    )
    print(
        f"UNCAPTURED {case.name.upper()} ONE-SHOT RESULT: "
        f"{after_comparison['result']} "
        f"({after_comparison['matches']}/{after_comparison['compared']})"
    )
    print(f"Write commands sent: 1; total UDP sends: {result.send_count}")
    print(f"Before temperature: {before['temperature']}")
    print(f"After temperature: {after['temperature']}")
    print(f"Report: {report}")
    return 0 if status == "passed" else 2


if __name__ == "__main__":
    raise SystemExit(main())
